version: '3.1'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_USER: thor
      MYSQL_PASSWORD: patrik
      MYSQL_DATABASE: todo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  app:
    build: ./apprealbe
    ports:
      - "4000:4000"
    restart: "always"
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apprealbe:/usr/src/apprealbe
      - /usr/src/apprealbe/node_modules

  fe:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: "always"
    depends_on:
      - app
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules 

